// Generated by scripts/assets/export_theme_catalog.py from the backend theme catalogue.
// Do not edit by hand; backend/tests/unit/test_theme_fixture.py checks it is current.
import type { ThemeCatalog } from '../../../shared/api/adminClient'

export const THEME_CATALOG: ThemeCatalog = {
  "tokens": [
    {
      "key": "background",
      "group": "Page",
      "label": "Page background",
      "description": "Behind everything, and around the background image."
    },
    {
      "key": "surface",
      "group": "Page",
      "label": "Cards and dialogs",
      "description": "Panels, cards and pop-up dialogs."
    },
    {
      "key": "overlay",
      "group": "Page",
      "label": "Backdrop",
      "description": "Dims the screen behind a dialog (shown see-through)."
    },
    {
      "key": "heading",
      "group": "Text",
      "label": "Headings",
      "description": "Titles such as the welcome heading."
    },
    {
      "key": "body",
      "group": "Text",
      "label": "Body text",
      "description": "Normal sentences and instructions."
    },
    {
      "key": "muted",
      "group": "Text",
      "label": "Helper text",
      "description": "Less important hints and captions."
    },
    {
      "key": "link",
      "group": "Text",
      "label": "Links",
      "description": "Text links guests can tap."
    },
    {
      "key": "primary_bg",
      "group": "Main button",
      "label": "Main button",
      "description": "The main action, e.g. Start."
    },
    {
      "key": "primary_text",
      "group": "Main button",
      "label": "Main button text",
      "description": "Label on the main button."
    },
    {
      "key": "primary_hover",
      "group": "Main button",
      "label": "Main button (hover)",
      "description": "When a pointer is over it."
    },
    {
      "key": "primary_pressed",
      "group": "Main button",
      "label": "Main button (pressed)",
      "description": "While it is being pressed."
    },
    {
      "key": "primary_disabled_bg",
      "group": "Main button",
      "label": "Main button (disabled)",
      "description": "When it can not be used yet."
    },
    {
      "key": "primary_disabled_text",
      "group": "Main button",
      "label": "Disabled main button text",
      "description": "Label while disabled."
    },
    {
      "key": "secondary_bg",
      "group": "Other buttons",
      "label": "Other buttons",
      "description": "Less important actions, e.g. Back."
    },
    {
      "key": "secondary_text",
      "group": "Other buttons",
      "label": "Other button text",
      "description": "Label on other buttons."
    },
    {
      "key": "secondary_hover",
      "group": "Other buttons",
      "label": "Other buttons (hover)",
      "description": "When a pointer is over it."
    },
    {
      "key": "secondary_pressed",
      "group": "Other buttons",
      "label": "Other buttons (pressed)",
      "description": "While it is being pressed."
    },
    {
      "key": "secondary_disabled_bg",
      "group": "Other buttons",
      "label": "Other buttons (disabled)",
      "description": "When it can not be used yet."
    },
    {
      "key": "secondary_disabled_text",
      "group": "Other buttons",
      "label": "Disabled other button text",
      "description": "Label while disabled."
    },
    {
      "key": "danger_bg",
      "group": "Other buttons",
      "label": "Delete / cancel button",
      "description": "Actions that remove something."
    },
    {
      "key": "danger_text",
      "group": "Other buttons",
      "label": "Delete / cancel button text",
      "description": "Label on that button."
    },
    {
      "key": "input_bg",
      "group": "Inputs",
      "label": "Input background",
      "description": "Inside text boxes, e.g. an email field."
    },
    {
      "key": "input_text",
      "group": "Inputs",
      "label": "Input text",
      "description": "What a guest types."
    },
    {
      "key": "input_border",
      "group": "Inputs",
      "label": "Input border",
      "description": "The outline of a text box."
    },
    {
      "key": "input_focus_border",
      "group": "Inputs",
      "label": "Input border (active)",
      "description": "Outline of the box being typed in."
    },
    {
      "key": "placeholder",
      "group": "Inputs",
      "label": "Example text in inputs",
      "description": "Grey example shown in an empty box."
    },
    {
      "key": "focus_ring",
      "group": "Inputs",
      "label": "Focus indicator",
      "description": "Ring around the control chosen by keyboard."
    },
    {
      "key": "success_bg",
      "group": "Messages",
      "label": "Success message",
      "description": "Background of a 'done' message."
    },
    {
      "key": "success_text",
      "group": "Messages",
      "label": "Success message text",
      "description": "Text of a 'done' message."
    },
    {
      "key": "warning_bg",
      "group": "Messages",
      "label": "Warning message",
      "description": "Background of a warning."
    },
    {
      "key": "warning_text",
      "group": "Messages",
      "label": "Warning message text",
      "description": "Text of a warning."
    },
    {
      "key": "error_bg",
      "group": "Messages",
      "label": "Error message",
      "description": "Background of an error."
    },
    {
      "key": "error_text",
      "group": "Messages",
      "label": "Error message text",
      "description": "Text of an error."
    },
    {
      "key": "info_bg",
      "group": "Messages",
      "label": "Information message",
      "description": "Background of a hint or notice."
    },
    {
      "key": "info_text",
      "group": "Messages",
      "label": "Information message text",
      "description": "Text of a hint or notice."
    }
  ],
  "contrast_rules": [
    {
      "foreground": "heading",
      "background": "background",
      "minimum": 4.5,
      "what": "Headings"
    },
    {
      "foreground": "heading",
      "background": "surface",
      "minimum": 4.5,
      "what": "Headings"
    },
    {
      "foreground": "body",
      "background": "background",
      "minimum": 4.5,
      "what": "Body text"
    },
    {
      "foreground": "body",
      "background": "surface",
      "minimum": 4.5,
      "what": "Body text"
    },
    {
      "foreground": "muted",
      "background": "background",
      "minimum": 4.5,
      "what": "Helper text"
    },
    {
      "foreground": "muted",
      "background": "surface",
      "minimum": 4.5,
      "what": "Helper text"
    },
    {
      "foreground": "link",
      "background": "background",
      "minimum": 4.5,
      "what": "Links"
    },
    {
      "foreground": "link",
      "background": "surface",
      "minimum": 4.5,
      "what": "Links"
    },
    {
      "foreground": "primary_text",
      "background": "primary_bg",
      "minimum": 4.5,
      "what": "Main button text"
    },
    {
      "foreground": "primary_text",
      "background": "primary_hover",
      "minimum": 4.5,
      "what": "Main button text"
    },
    {
      "foreground": "primary_text",
      "background": "primary_pressed",
      "minimum": 4.5,
      "what": "Main button text"
    },
    {
      "foreground": "secondary_text",
      "background": "secondary_bg",
      "minimum": 4.5,
      "what": "Other button text"
    },
    {
      "foreground": "secondary_text",
      "background": "secondary_hover",
      "minimum": 4.5,
      "what": "Other button text"
    },
    {
      "foreground": "secondary_text",
      "background": "secondary_pressed",
      "minimum": 4.5,
      "what": "Other button text"
    },
    {
      "foreground": "danger_text",
      "background": "danger_bg",
      "minimum": 4.5,
      "what": "Delete button text"
    },
    {
      "foreground": "input_text",
      "background": "input_bg",
      "minimum": 4.5,
      "what": "Input text"
    },
    {
      "foreground": "placeholder",
      "background": "input_bg",
      "minimum": 4.5,
      "what": "Example text in inputs"
    },
    {
      "foreground": "success_text",
      "background": "success_bg",
      "minimum": 4.5,
      "what": "Success message"
    },
    {
      "foreground": "warning_text",
      "background": "warning_bg",
      "minimum": 4.5,
      "what": "Warning message"
    },
    {
      "foreground": "error_text",
      "background": "error_bg",
      "minimum": 4.5,
      "what": "Error message"
    },
    {
      "foreground": "info_text",
      "background": "info_bg",
      "minimum": 4.5,
      "what": "Information message"
    },
    {
      "foreground": "primary_disabled_text",
      "background": "primary_disabled_bg",
      "minimum": 3.0,
      "what": "Disabled main button"
    },
    {
      "foreground": "secondary_disabled_text",
      "background": "secondary_disabled_bg",
      "minimum": 3.0,
      "what": "Disabled other button"
    },
    {
      "foreground": "input_border",
      "background": "input_bg",
      "minimum": 3.0,
      "what": "Input border"
    },
    {
      "foreground": "input_focus_border",
      "background": "input_bg",
      "minimum": 3.0,
      "what": "Active input border"
    },
    {
      "foreground": "focus_ring",
      "background": "background",
      "minimum": 3.0,
      "what": "Focus indicator"
    },
    {
      "foreground": "focus_ring",
      "background": "surface",
      "minimum": 3.0,
      "what": "Focus indicator on cards"
    }
  ],
  "presets": [
    {
      "id": "midnight_blue",
      "name": "Midnight Blue",
      "description": "Deep navy with a bright blue button and warm amber.",
      "frame_family": "midnight",
      "tokens": {
        "background": "#0F172A",
        "surface": "#222A3B",
        "overlay": "#000000",
        "heading": "#F8FAFC",
        "body": "#E1E3E7",
        "muted": "#A4A8B0",
        "link": "#4F8FF7",
        "primary_bg": "#156AF4",
        "primary_text": "#F8FAFC",
        "primary_hover": "#0B5CE0",
        "primary_pressed": "#0950C3",
        "primary_disabled_bg": "#123C85",
        "primary_disabled_text": "#A8B8D2",
        "secondary_bg": "#F59E0B",
        "secondary_text": "#0F172A",
        "secondary_hover": "#F6AA28",
        "secondary_pressed": "#F7B546",
        "secondary_disabled_bg": "#76541C",
        "secondary_disabled_text": "#030302",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#222A3B",
        "input_text": "#F8FAFC",
        "input_border": "#8D929C",
        "input_focus_border": "#156AF4",
        "placeholder": "#A4A8B0",
        "focus_ring": "#4F8FF7",
        "success_bg": "#203D3D",
        "success_text": "#19BD56",
        "warning_bg": "#3F3633",
        "warning_text": "#F38507",
        "error_bg": "#402938",
        "error_text": "#E97777",
        "info_bg": "#223357",
        "info_text": "#739BF2"
      }
    },
    {
      "id": "minimal_light",
      "name": "Minimal Light",
      "description": "Clean white with a crisp blue accent.",
      "frame_family": "minimal_light",
      "tokens": {
        "background": "#F8FAFC",
        "surface": "#FDFEFE",
        "overlay": "#0F172A",
        "heading": "#0F172A",
        "body": "#262E3F",
        "muted": "#636976",
        "link": "#2563EB",
        "primary_bg": "#2563EB",
        "primary_text": "#F8FAFC",
        "primary_hover": "#1453DD",
        "primary_pressed": "#1249C1",
        "primary_disabled_bg": "#99B6F4",
        "primary_disabled_text": "#1F59D0",
        "secondary_bg": "#0F172A",
        "secondary_text": "#F8FAFC",
        "secondary_hover": "#070B13",
        "secondary_pressed": "#000000",
        "secondary_disabled_bg": "#8F949E",
        "secondary_disabled_text": "#FFFFFF",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#FFFFFF",
        "input_text": "#0F172A",
        "input_border": "#878B94",
        "input_focus_border": "#2563EB",
        "placeholder": "#636976",
        "focus_ring": "#2563EB",
        "success_bg": "#D8EFE1",
        "success_text": "#107937",
        "warning_bg": "#F7E8D6",
        "warning_text": "#9F5704",
        "error_bg": "#F8DBDB",
        "error_text": "#C11F1F",
        "info_bg": "#DAE5FB",
        "info_text": "#1558EA"
      }
    },
    {
      "id": "celebration_gold",
      "name": "Celebration Gold",
      "description": "Warm espresso with festive gold.",
      "frame_family": "celebration_gold",
      "tokens": {
        "background": "#1C1917",
        "surface": "#2E2B2A",
        "overlay": "#000000",
        "heading": "#F8FAFC",
        "body": "#E2E4E5",
        "muted": "#A9A9AA",
        "link": "#D4A017",
        "primary_bg": "#D4A017",
        "primary_text": "#0F172A",
        "primary_hover": "#E7B123",
        "primary_pressed": "#EABB3E",
        "primary_disabled_bg": "#6F5617",
        "primary_disabled_text": "#000000",
        "secondary_bg": "#F5E6C8",
        "secondary_text": "#0F172A",
        "secondary_hover": "#FAF2E2",
        "secondary_pressed": "#FEFEFC",
        "secondary_disabled_bg": "#7E7567",
        "secondary_disabled_text": "#2A2C31",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#2E2B2A",
        "input_text": "#F8FAFC",
        "input_border": "#939293",
        "input_focus_border": "#D4A017",
        "placeholder": "#A9A9AA",
        "focus_ring": "#D4A017",
        "success_bg": "#2A3E2F",
        "success_text": "#19BD56",
        "warning_bg": "#493724",
        "warning_text": "#F88807",
        "error_bg": "#4A2A29",
        "error_text": "#EA7B7B",
        "info_bg": "#2D3449",
        "info_text": "#739BF2"
      }
    },
    {
      "id": "blush_wedding",
      "name": "Blush Wedding",
      "description": "Soft blush pink with deep rose.",
      "frame_family": "minimal_light",
      "tokens": {
        "background": "#FFF1F2",
        "surface": "#FFFCFC",
        "overlay": "#0F172A",
        "heading": "#0F172A",
        "body": "#272D3E",
        "muted": "#656572",
        "link": "#BE185D",
        "primary_bg": "#BE185D",
        "primary_text": "#F8FAFC",
        "primary_hover": "#A31550",
        "primary_pressed": "#881142",
        "primary_disabled_bg": "#E28FAF",
        "primary_disabled_text": "#93345E",
        "secondary_bg": "#9F1239",
        "secondary_text": "#F8FAFC",
        "secondary_hover": "#840F2F",
        "secondary_pressed": "#680C25",
        "secondary_disabled_bg": "#D48D9F",
        "secondary_disabled_text": "#813C51",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#FFFFFF",
        "input_text": "#0F172A",
        "input_border": "#878B94",
        "input_focus_border": "#BE185D",
        "placeholder": "#656572",
        "focus_ring": "#BE185D",
        "success_bg": "#DAEEE0",
        "success_text": "#107937",
        "warning_bg": "#F9E7D5",
        "warning_text": "#9F5704",
        "error_bg": "#F9DADA",
        "error_text": "#C11F1F",
        "info_bg": "#DCE4F9",
        "info_text": "#1558EA"
      }
    },
    {
      "id": "forest_fresh",
      "name": "Forest Fresh",
      "description": "Light mint with forest green.",
      "frame_family": "minimal_light",
      "tokens": {
        "background": "#F0FDF4",
        "surface": "#FBFEFC",
        "overlay": "#0F172A",
        "heading": "#0F172A",
        "body": "#262E3E",
        "muted": "#606A73",
        "link": "#15803D",
        "primary_bg": "#15803D",
        "primary_text": "#F8FAFC",
        "primary_hover": "#116630",
        "primary_pressed": "#0C4B24",
        "primary_disabled_bg": "#8DC5A2",
        "primary_disabled_text": "#3B6D52",
        "secondary_bg": "#065F46",
        "secondary_text": "#F8FAFC",
        "secondary_hover": "#044231",
        "secondary_pressed": "#02251C",
        "secondary_disabled_bg": "#87B6A6",
        "secondary_disabled_text": "#3C6259",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#FFFFFF",
        "input_text": "#0F172A",
        "input_border": "#878B94",
        "input_focus_border": "#15803D",
        "placeholder": "#606A73",
        "focus_ring": "#15803D",
        "success_bg": "#D6EFE0",
        "success_text": "#107937",
        "warning_bg": "#F6E8D5",
        "warning_text": "#9F5704",
        "error_bg": "#F6DBDA",
        "error_text": "#C11F1F",
        "info_bg": "#D9E5F9",
        "info_text": "#1558EA"
      }
    },
    {
      "id": "neon_party",
      "name": "Neon Party",
      "description": "Dark violet with neon magenta and cyan.",
      "frame_family": "midnight",
      "tokens": {
        "background": "#140B2E",
        "surface": "#271F3F",
        "overlay": "#000000",
        "heading": "#F8FAFC",
        "body": "#E1E2E7",
        "muted": "#A6A4B2",
        "link": "#D948EF",
        "primary_bg": "#D946EF",
        "primary_text": "#0F172A",
        "primary_hover": "#DF62F1",
        "primary_pressed": "#E57EF4",
        "primary_disabled_bg": "#6D2685",
        "primary_disabled_text": "#A685D1",
        "secondary_bg": "#22D3EE",
        "secondary_text": "#0F172A",
        "secondary_hover": "#3ED9F0",
        "secondary_pressed": "#5BDEF2",
        "secondary_disabled_bg": "#1A6584",
        "secondary_disabled_text": "#050E14",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#271F3F",
        "input_text": "#F8FAFC",
        "input_border": "#908C9E",
        "input_focus_border": "#D946EF",
        "placeholder": "#A6A4B2",
        "focus_ring": "#D948EF",
        "success_bg": "#243441",
        "success_text": "#18B452",
        "warning_bg": "#432D36",
        "warning_text": "#E98006",
        "error_bg": "#44203B",
        "error_text": "#E86E6E",
        "info_bg": "#272A5B",
        "info_text": "#6A94F1"
      }
    },
    {
      "id": "sunset_coral",
      "name": "Sunset Coral",
      "description": "Warm cream with coral orange.",
      "frame_family": "celebration_gold",
      "tokens": {
        "background": "#FFF7ED",
        "surface": "#FFFDFA",
        "overlay": "#0F172A",
        "heading": "#0F172A",
        "body": "#272D3E",
        "muted": "#656870",
        "link": "#C2490A",
        "primary_bg": "#C74B0A",
        "primary_text": "#F8FAFC",
        "primary_hover": "#AA4009",
        "primary_pressed": "#8D3507",
        "primary_disabled_bg": "#E6AA87",
        "primary_disabled_text": "#924F2B",
        "secondary_bg": "#7C2D12",
        "secondary_text": "#F8FAFC",
        "secondary_hover": "#61230E",
        "secondary_pressed": "#471A0A",
        "secondary_disabled_bg": "#C49C8A",
        "secondary_disabled_text": "#6E4C40",
        "danger_bg": "#DC2626",
        "danger_text": "#F8FAFC",
        "input_bg": "#FFFFFF",
        "input_text": "#0F172A",
        "input_border": "#878B94",
        "input_focus_border": "#C74B0A",
        "placeholder": "#656870",
        "focus_ring": "#C2490A",
        "success_bg": "#DAEFDE",
        "success_text": "#107937",
        "warning_bg": "#F9E8D3",
        "warning_text": "#9F5704",
        "error_bg": "#F9DBD8",
        "error_text": "#C11F1F",
        "info_bg": "#DCE4F8",
        "info_text": "#1558EA"
      }
    }
  ],
  "default_preset": "midnight_blue"
}
