/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_api_admin_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Metadata */
        get: operations["asset_metadata_api_admin_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/assets/{asset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Content */
        get: operations["asset_content_api_admin_assets__asset_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_admin_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Frames */
        get: operations["list_frames_api_admin_frames_get"];
        put?: never;
        /** Upload Frame */
        post: operations["upload_frame_api_admin_frames_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/frames/{frame_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frame Metadata */
        get: operations["frame_metadata_api_admin_frames__frame_id__get"];
        put?: never;
        post?: never;
        /** Delete Frame */
        delete: operations["delete_frame_api_admin_frames__frame_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/frames/{frame_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Frame Content
         * @description The original uploaded PNG, byte for byte.
         */
        get: operations["frame_content_api_admin_frames__frame_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/frames/{frame_id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename Frame */
        put: operations["rename_frame_api_admin_frames__frame_id__name_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/frames/{frame_id}/preview/{output_index}.jpg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Frame Preview
         * @description Sample output: numbered placeholder photos with this frame composited on top.
         */
        get: operations["frame_preview_api_admin_frames__frame_id__preview__output_index__jpg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/frames/{frame_id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Frame
         * @description Swap in a corrected PNG. Profiles keep their selection; the old file is kept unchanged.
         */
        post: operations["replace_frame_api_admin_frames__frame_id__replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_admin_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_admin_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_admin_profiles__profile_id__get"];
        /** Update Profile */
        put: operations["update_profile_api_admin_profiles__profile_id__put"];
        post?: never;
        /**
         * Delete Profile
         * @description Soft delete: the row and its assets stay; it can be restored.
         */
        delete: operations["delete_profile_api_admin_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profiles/{profile_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Profile */
        post: operations["activate_profile_api_admin_profiles__profile_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profiles/{profile_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Profile */
        post: operations["duplicate_profile_api_admin_profiles__profile_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profiles/{profile_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Profile */
        post: operations["restore_profile_api_admin_profiles__profile_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booth/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Booth Ping */
        post: operations["booth_ping_api_booth_ping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiosk Status */
        get: operations["kiosk_status_api_kiosk_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render/samples/{key}/{output_index}.jpg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Output */
        get: operations["sample_output_api_render_samples__key___output_index__jpg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template Spec */
        get: operations["template_spec_api_templates__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{key}/blank.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blank Png */
        get: operations["blank_png_api_templates__key__blank_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{key}/guide.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guide Png */
        get: operations["guide_png_api_templates__key__guide_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kiosk/pairing-code/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Pairing Code */
        post: operations["rotate_pairing_code_kiosk_pairing_code_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "logo" | "background" | "frame";
        /**
         * DeliveryMode
         * @enum {string}
         */
        DeliveryMode: "local_link";
        /** DuplicateBody */
        DuplicateBody: {
            /** Name */
            name?: string | null;
        };
        /** EventProfileResponse */
        EventProfileResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Revision */
            revision: number;
            settings: components["schemas"]["ProfileSettingsBody"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FrameResponse
         * @description A validated frame. The stored file itself is served by `/content`.
         */
        FrameResponse: {
            /** Bytes */
            bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
            /** Slot Transparency */
            slot_transparency: number[];
            /** Status */
            status: string;
            /** Template Key */
            template_key: string;
            /** Template Version */
            template_version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Warnings */
            warnings: string[];
            /** Width */
            width: number;
        };
        /** FrameRulesModel */
        FrameRulesModel: {
            /** Animated */
            animated: boolean;
            /** Color */
            color: string;
            /** Exact Size */
            exact_size: boolean;
            /** Format */
            format: string;
            /** Max Bytes */
            max_bytes: number;
            /** Mode */
            mode: string;
            /** Slot Min Transparency */
            slot_min_transparency: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /** Instance */
            instance: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** KioskStatusResponse */
        KioskStatusResponse: {
            /** Paired */
            paired: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * MediaAssetResponse
         * @description Stored asset metadata. The storage key and client file name are never exposed.
         */
        MediaAssetResponse: {
            /** Bytes */
            bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            kind: components["schemas"]["AssetKind"];
            /** Mime */
            mime: string;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
        };
        /** PingResponse */
        PingResponse: {
            /** Ok */
            ok: boolean;
        };
        /** ProblemResponse */
        ProblemResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ProfileSettingsBody
         * @description Every field an organizer can set. Unknown fields are refused.
         */
        ProfileSettingsBody: {
            /** Background Asset Id */
            background_asset_id?: string | null;
            /**
             * Background Color
             * @default #101418
             * @example #2F6FD6
             */
            background_color: string;
            /**
             * Button Color
             * @default #2F6FD6
             * @example #2F6FD6
             */
            button_color: string;
            /**
             * Countdown Seconds
             * @default 5
             * @constant
             */
            countdown_seconds: 5;
            /** @default local_link */
            delivery_mode: components["schemas"]["DeliveryMode"];
            /** Enabled Layouts */
            enabled_layouts: string[];
            /** Frame Selections */
            frame_selections?: {
                [key: string]: string;
            };
            /**
             * Inactivity Timeout S
             * @default 120
             */
            inactivity_timeout_s: number;
            /** Logo Asset Id */
            logo_asset_id?: string | null;
            /**
             * Mirror
             * @default true
             */
            mirror: boolean;
            /** Name */
            name: string;
            /**
             * Primary Color
             * @default #2F6FD6
             * @example #2F6FD6
             */
            primary_color: string;
            /** @default per_photo */
            retake_mode: components["schemas"]["RetakeMode"];
            /**
             * Secondary Color
             * @default #FFB020
             * @example #2F6FD6
             */
            secondary_color: string;
            /**
             * Start Button Text
             * @default Start
             */
            start_button_text: string;
            /**
             * Subtitle
             * @description Preparation screen text
             * @default
             */
            subtitle: string;
            /**
             * Text Color
             * @default #F4F6F8
             * @example #2F6FD6
             */
            text_color: string;
            /**
             * Title
             * @description Preparation screen title
             */
            title: string;
        };
        /** ProfileUpdateBody */
        ProfileUpdateBody: {
            /** Background Asset Id */
            background_asset_id?: string | null;
            /**
             * Background Color
             * @default #101418
             * @example #2F6FD6
             */
            background_color: string;
            /**
             * Button Color
             * @default #2F6FD6
             * @example #2F6FD6
             */
            button_color: string;
            /**
             * Countdown Seconds
             * @default 5
             * @constant
             */
            countdown_seconds: 5;
            /** @default local_link */
            delivery_mode: components["schemas"]["DeliveryMode"];
            /** Enabled Layouts */
            enabled_layouts: string[];
            /** Frame Selections */
            frame_selections?: {
                [key: string]: string;
            };
            /**
             * Inactivity Timeout S
             * @default 120
             */
            inactivity_timeout_s: number;
            /** Logo Asset Id */
            logo_asset_id?: string | null;
            /**
             * Mirror
             * @default true
             */
            mirror: boolean;
            /** Name */
            name: string;
            /**
             * Primary Color
             * @default #2F6FD6
             * @example #2F6FD6
             */
            primary_color: string;
            /** @default per_photo */
            retake_mode: components["schemas"]["RetakeMode"];
            /**
             * Revision
             * @description Revision the edit was based on (optimistic lock)
             */
            revision: number;
            /**
             * Secondary Color
             * @default #FFB020
             * @example #2F6FD6
             */
            secondary_color: string;
            /**
             * Start Button Text
             * @default Start
             */
            start_button_text: string;
            /**
             * Subtitle
             * @description Preparation screen text
             * @default
             */
            subtitle: string;
            /**
             * Text Color
             * @default #F4F6F8
             * @example #2F6FD6
             */
            text_color: string;
            /**
             * Title
             * @description Preparation screen title
             */
            title: string;
        };
        /** RectModel */
        RectModel: {
            /** H */
            h: number;
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RenameFrameBody */
        RenameFrameBody: {
            /** Name */
            name: string;
        };
        /**
         * RetakeMode
         * @enum {string}
         */
        RetakeMode: "none" | "per_photo" | "all";
        /** SessionResponse */
        SessionResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Username */
            username: string;
        };
        /** SlotModel */
        SlotModel: {
            /** Anchor */
            anchor: string;
            /** Aspect */
            aspect: string;
            /** Fit */
            fit: string;
            /** H */
            h: number;
            /** Index */
            index: number;
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** TemplateLinks */
        TemplateLinks: {
            /** Blank Png */
            blank_png: string;
            /** Guide Png */
            guide_png: string;
            /** Sample Jpgs */
            sample_jpgs: string[];
            /** Spec */
            spec: string;
        };
        /** TemplateSpec */
        TemplateSpec: {
            /** Bleed */
            bleed: number;
            branding_area: components["schemas"]["RectModel"] | null;
            /** Captures Per Session */
            captures_per_session: number;
            /** Dpi */
            dpi: number;
            /** Frame Requirements */
            frame_requirements: string[];
            frame_rules: components["schemas"]["FrameRulesModel"];
            /** Height In */
            height_in: number;
            /** Height Px */
            height_px: number;
            /** Key */
            key: string;
            links: components["schemas"]["TemplateLinks"];
            /** Name */
            name: string;
            /** Orientation */
            orientation: string;
            /** Output Capture Groups */
            output_capture_groups: number[][];
            /** Outputs Per Session */
            outputs_per_session: number;
            /** Photos Per Output */
            photos_per_output: number;
            safe_area: components["schemas"]["RectModel"];
            /** Safe Area Inset */
            safe_area_inset: number;
            /** Slots */
            slots: components["schemas"]["SlotModel"][];
            /** Version */
            version: number;
            /** Width In */
            width_in: number;
            /** Width Px */
            width_px: number;
        };
        /** TemplateSummary */
        TemplateSummary: {
            /** Captures Per Session */
            captures_per_session: number;
            /** Dpi */
            dpi: number;
            /** Height In */
            height_in: number;
            /** Height Px */
            height_px: number;
            /** Key */
            key: string;
            links: components["schemas"]["TemplateLinks"];
            /** Name */
            name: string;
            /** Orientation */
            orientation: string;
            /** Outputs Per Session */
            outputs_per_session: number;
            /** Photos Per Output */
            photos_per_output: number;
            /** Version */
            version: number;
            /** Width In */
            width_in: number;
            /** Width Px */
            width_px: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Api Version */
            api_version: number;
            /** App Version */
            app_version: string;
            /** Git Commit */
            git_commit: string | null;
            /** Instance */
            instance: string;
            /** Schema Revision */
            schema_revision: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_asset_api_admin_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @enum {string} */
                    kind: "logo" | "background";
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetResponse"];
                };
            };
        };
    };
    asset_metadata_api_admin_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_content_api_admin_assets__asset_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_admin_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current_session_api_admin_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    list_frames_api_admin_frames_get: {
        parameters: {
            query?: {
                template_key?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_frame_api_admin_frames_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @example Expo blue border */
                    name: string;
                    /** @example strip_2x6 */
                    template_key: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameResponse"];
                };
            };
        };
    };
    frame_metadata_api_admin_frames__frame_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frame_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_frame_api_admin_frames__frame_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frame_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frame_content_api_admin_frames__frame_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frame_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_frame_api_admin_frames__frame_id__name_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frame_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameFrameBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frame_preview_api_admin_frames__frame_id__preview__output_index__jpg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frame_id: string;
                output_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_frame_api_admin_frames__frame_id__replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frame_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_admin_profiles_get: {
        parameters: {
            query?: {
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_api_admin_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_admin_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_admin_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_admin_profiles__profile_id__delete: {
        parameters: {
            query: {
                revision: number;
            };
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_profile_api_admin_profiles__profile_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_profile_api_admin_profiles__profile_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DuplicateBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_profile_api_admin_profiles__profile_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProfileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    booth_ping_api_booth_ping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    kiosk_status_api_kiosk_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskStatusResponse"];
                };
            };
        };
    };
    sample_output_api_render_samples__key___output_index__jpg_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
                output_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSummary"][];
                };
            };
        };
    };
    template_spec_api_templates__key__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blank_png_api_templates__key__blank_png_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guide_png_api_templates__key__guide_png_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    rotate_pairing_code_kiosk_pairing_code_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
