"""Write the theme catalogue (GET /api/admin/themes) as the frontend test fixture.

Run from the repository root with the backend virtualenv:
    backend\\.venv\\Scripts\\python.exe scripts\\assets\\export_theme_catalog.py

`backend/tests/unit/test_theme_fixture.py` fails when the fixture is out of date.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from photobooth.modules.themes.domain import DEFAULT_PRESET, PRESET_LIST
from photobooth.modules.themes.schemas import ThemeCatalogResponse

FIXTURE = (
    Path(__file__).resolve().parents[2]
    / "frontend"
    / "src"
    / "features"
    / "admin"
    / "testing"
    / "themeCatalog.fixture.ts"
)
HEADER = (
    "// Generated by scripts/assets/export_theme_catalog.py from the backend theme catalogue.\n"
    "// Do not edit by hand; backend/tests/unit/test_theme_fixture.py checks it is current.\n"
    "import type { ThemeCatalog } from '../../../shared/api/adminClient'\n\n"
    "export const THEME_CATALOG: ThemeCatalog = "
)


def catalogue_json() -> str:
    data = ThemeCatalogResponse.of(PRESET_LIST, DEFAULT_PRESET).model_dump(mode="json")
    return json.dumps(data, indent=2, ensure_ascii=False)


def render() -> str:
    return HEADER + catalogue_json() + "\n"


def main() -> int:
    FIXTURE.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {FIXTURE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
